// Seed data for the New Arrivals shelf. These appear alongside any rows in
// the `recent_arrivals` Postgres table so the shelf is never empty and stays
// populated even when the database hasn't been provisioned yet.
//
// Cover images are pulled from Open Library by ISBN — they fall back to a
// blank image if a cover hasn't been uploaded yet, which the UI handles.

export interface SeedArrival {
  id: string;
  sku: string;
  isbn: string;
  title: string;
  author: string;
  co_author: string;
  series: string;
  series_number: string;
  category: string;
  subcategory: string;
  format: string;
  publisher: string;
  pub_year: number;
  verified: "verified" | "verify";
  cover_url: string;
  list_price: number;
  added_at: string;
  notes: string;
}

function cover(isbn: string): string {
  return `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;
}

// Stagger added_at so the existing `ORDER BY added_at DESC` produces a stable
// ordering that matches the SKU sequence (NA-001 first → NA-038 last).
function stagger(index: number): string {
  const base = new Date("2026-06-13T18:00:00Z").getTime();
  return new Date(base - index * 60_000).toISOString();
}

// Refreshed arrivals — popular, widely-stocked used-bookstore titles. Every ISBN
// below has a confirmed Open Library cover (verified against
// covers.openlibrary.org/b/isbn/<isbn>-L.jpg), so the shelf always renders real
// jackets rather than blank placeholders.
const rows: Omit<SeedArrival, "id" | "cover_url" | "added_at">[] = [
  { sku: "NA-001", isbn: "9781250301697", title: "The Silent Patient", author: "Alex Michaelides", co_author: "", series: "", series_number: "", category: "thriller_psychological", subcategory: "suspense", format: "paperback", publisher: "Celadon Books", pub_year: 2019, verified: "verified", list_price: 17.99, notes: "" },
  { sku: "NA-002", isbn: "9780735219090", title: "Where the Crawdads Sing", author: "Delia Owens", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "book_club", format: "paperback", publisher: "G.P. Putnam's Sons", pub_year: 2018, verified: "verified", list_price: 18.0, notes: "" },
  { sku: "NA-003", isbn: "9780525559474", title: "The Midnight Library", author: "Matt Haig", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "contemporary", format: "paperback", publisher: "Viking", pub_year: 2020, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-004", isbn: "9781501110368", title: "It Ends with Us", author: "Colleen Hoover", co_author: "", series: "", series_number: "", category: "romance_contemporary", subcategory: "book_club", format: "paperback", publisher: "Atria Books", pub_year: 2016, verified: "verified", list_price: 16.99, notes: "" },
  { sku: "NA-005", isbn: "9781538724736", title: "Verity", author: "Colleen Hoover", co_author: "", series: "", series_number: "", category: "thriller_psychological", subcategory: "romantic_suspense", format: "paperback", publisher: "Grand Central Publishing", pub_year: 2021, verified: "verified", list_price: 16.99, notes: "" },
  { sku: "NA-006", isbn: "9780735211292", title: "Atomic Habits", author: "James Clear", co_author: "", series: "", series_number: "", category: "literary_nonfiction", subcategory: "self_help", format: "hardcover", publisher: "Avery", pub_year: 2018, verified: "verified", list_price: 27.0, notes: "" },
  { sku: "NA-007", isbn: "9781538742570", title: "The Housemaid", author: "Freida McFadden", co_author: "", series: "The Housemaid", series_number: "1", category: "thriller_psychological", subcategory: "suspense", format: "paperback", publisher: "Grand Central Publishing", pub_year: 2022, verified: "verified", list_price: 17.99, notes: "" },
  { sku: "NA-008", isbn: "9780307588371", title: "Gone Girl", author: "Gillian Flynn", co_author: "", series: "", series_number: "", category: "thriller_psychological", subcategory: "suspense", format: "paperback", publisher: "Crown", pub_year: 2012, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-009", isbn: "9781594634024", title: "The Girl on the Train", author: "Paula Hawkins", co_author: "", series: "", series_number: "", category: "thriller_psychological", subcategory: "suspense", format: "paperback", publisher: "Riverhead Books", pub_year: 2015, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-010", isbn: "9780804172707", title: "A Little Life", author: "Hanya Yanagihara", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "contemporary", format: "paperback", publisher: "Anchor", pub_year: 2015, verified: "verified", list_price: 18.0, notes: "" },
  { sku: "NA-011", isbn: "9780399590504", title: "Educated", author: "Tara Westover", co_author: "", series: "", series_number: "", category: "literary_nonfiction", subcategory: "memoir", format: "paperback", publisher: "Random House", pub_year: 2018, verified: "verified", list_price: 18.0, notes: "" },
  { sku: "NA-012", isbn: "9780316556347", title: "Circe", author: "Madeline Miller", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "mythology", format: "paperback", publisher: "Back Bay Books", pub_year: 2018, verified: "verified", list_price: 17.99, notes: "" },
  { sku: "NA-013", isbn: "9780062060624", title: "The Song of Achilles", author: "Madeline Miller", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "mythology", format: "paperback", publisher: "Ecco", pub_year: 2011, verified: "verified", list_price: 17.99, notes: "" },
  { sku: "NA-014", isbn: "9781984822178", title: "Normal People", author: "Sally Rooney", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "contemporary", format: "paperback", publisher: "Hogarth", pub_year: 2019, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-015", isbn: "9780593135204", title: "Project Hail Mary", author: "Andy Weir", co_author: "", series: "", series_number: "", category: "science_fiction", subcategory: "adventure", format: "hardcover", publisher: "Ballantine Books", pub_year: 2021, verified: "verified", list_price: 28.99, notes: "" },
  { sku: "NA-016", isbn: "9780312577223", title: "The Nightingale", author: "Kristin Hannah", co_author: "", series: "", series_number: "", category: "historical_fiction", subcategory: "wwii", format: "paperback", publisher: "St. Martin's Griffin", pub_year: 2015, verified: "verified", list_price: 17.99, notes: "" },
  { sku: "NA-017", isbn: "9780385547345", title: "Lessons in Chemistry", author: "Bonnie Garmus", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "book_club", format: "hardcover", publisher: "Doubleday", pub_year: 2022, verified: "verified", list_price: 29.0, notes: "" },
  { sku: "NA-018", isbn: "9781649374042", title: "Fourth Wing", author: "Rebecca Yarros", co_author: "", series: "The Empyrean", series_number: "1", category: "fantasy_romance", subcategory: "romantasy", format: "hardcover", publisher: "Entangled: Red Tower Books", pub_year: 2023, verified: "verified", list_price: 29.99, notes: "" },
  { sku: "NA-019", isbn: "9781649374172", title: "Iron Flame", author: "Rebecca Yarros", co_author: "", series: "The Empyrean", series_number: "2", category: "fantasy_romance", subcategory: "romantasy", format: "hardcover", publisher: "Entangled: Red Tower Books", pub_year: 2023, verified: "verified", list_price: 29.99, notes: "" },
  { sku: "NA-020", isbn: "9781619634442", title: "A Court of Thorns and Roses", author: "Sarah J. Maas", co_author: "", series: "A Court of Thorns and Roses", series_number: "1", category: "fantasy_romance", subcategory: "romantasy", format: "paperback", publisher: "Bloomsbury", pub_year: 2015, verified: "verified", list_price: 19.0, notes: "" },
  { sku: "NA-021", isbn: "9780765326355", title: "The Way of Kings", author: "Brandon Sanderson", co_author: "", series: "The Stormlight Archive", series_number: "1", category: "fantasy_epic", subcategory: "high_fantasy", format: "paperback", publisher: "Tor Books", pub_year: 2010, verified: "verified", list_price: 24.99, notes: "" },
  { sku: "NA-022", isbn: "9780063251922", title: "Demon Copperhead", author: "Barbara Kingsolver", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "book_club", format: "paperback", publisher: "Harper", pub_year: 2022, verified: "verified", list_price: 19.99, notes: "Pulitzer Prize winner" },
  { sku: "NA-023", isbn: "9780141439518", title: "Pride and Prejudice", author: "Jane Austen", co_author: "", series: "", series_number: "", category: "literary_classic", subcategory: "classic", format: "paperback", publisher: "Penguin Classics", pub_year: 1813, verified: "verified", list_price: 12.0, notes: "" },
  { sku: "NA-024", isbn: "9780451524935", title: "1984", author: "George Orwell", co_author: "", series: "", series_number: "", category: "literary_classic", subcategory: "dystopian", format: "paperback", publisher: "Signet Classics", pub_year: 1949, verified: "verified", list_price: 9.99, notes: "" },
  { sku: "NA-025", isbn: "9780743273565", title: "The Great Gatsby", author: "F. Scott Fitzgerald", co_author: "", series: "", series_number: "", category: "literary_classic", subcategory: "classic", format: "paperback", publisher: "Scribner", pub_year: 1925, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-026", isbn: "9780525536291", title: "The Vanishing Half", author: "Brit Bennett", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "book_club", format: "paperback", publisher: "Riverhead Books", pub_year: 2020, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-027", isbn: "9781984806734", title: "Beach Read", author: "Emily Henry", co_author: "", series: "", series_number: "", category: "romance_contemporary", subcategory: "contemporary", format: "paperback", publisher: "Berkley", pub_year: 2020, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-028", isbn: "9780593334836", title: "Book Lovers", author: "Emily Henry", co_author: "", series: "", series_number: "", category: "romance_contemporary", subcategory: "contemporary", format: "paperback", publisher: "Berkley", pub_year: 2022, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-029", isbn: "9780593336823", title: "The Love Hypothesis", author: "Ali Hazelwood", co_author: "", series: "", series_number: "", category: "romance_contemporary", subcategory: "stem", format: "paperback", publisher: "Berkley", pub_year: 2021, verified: "verified", list_price: 16.0, notes: "" },
  { sku: "NA-030", isbn: "9780593441275", title: "Happy Place", author: "Emily Henry", co_author: "", series: "", series_number: "", category: "romance_contemporary", subcategory: "contemporary", format: "paperback", publisher: "Berkley", pub_year: 2023, verified: "verified", list_price: 19.0, notes: "" },
  { sku: "NA-031", isbn: "9780593356159", title: "The Maid", author: "Nita Prose", co_author: "", series: "Molly the Maid", series_number: "1", category: "thriller_psychological", subcategory: "cozy_mystery", format: "paperback", publisher: "Ballantine Books", pub_year: 2022, verified: "verified", list_price: 18.0, notes: "" },
  { sku: "NA-032", isbn: "9780063204157", title: "Remarkably Bright Creatures", author: "Shelby Van Pelt", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "book_club", format: "paperback", publisher: "Ecco", pub_year: 2022, verified: "verified", list_price: 18.99, notes: "" },
  { sku: "NA-033", isbn: "9780593243732", title: "Hello Beautiful", author: "Ann Napolitano", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "book_club", format: "hardcover", publisher: "Dial Press", pub_year: 2023, verified: "verified", list_price: 28.0, notes: "" },
  { sku: "NA-034", isbn: "9780593321201", title: "Tomorrow, and Tomorrow, and Tomorrow", author: "Gabrielle Zevin", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "contemporary", format: "hardcover", publisher: "Knopf", pub_year: 2022, verified: "verified", list_price: 28.0, notes: "" },
  { sku: "NA-035", isbn: "9780061120084", title: "To Kill a Mockingbird", author: "Harper Lee", co_author: "", series: "", series_number: "", category: "literary_classic", subcategory: "classic", format: "paperback", publisher: "Harper Perennial Modern Classics", pub_year: 1960, verified: "verified", list_price: 17.99, notes: "" },
  { sku: "NA-036", isbn: "9780399501487", title: "Lord of the Flies", author: "William Golding", co_author: "", series: "", series_number: "", category: "literary_classic", subcategory: "classic", format: "paperback", publisher: "Penguin Books", pub_year: 1954, verified: "verified", list_price: 12.0, notes: "" },
  { sku: "NA-037", isbn: "9780316769488", title: "The Catcher in the Rye", author: "J.D. Salinger", co_author: "", series: "", series_number: "", category: "literary_classic", subcategory: "classic", format: "paperback", publisher: "Little, Brown and Company", pub_year: 1951, verified: "verified", list_price: 9.99, notes: "" },
  { sku: "NA-038", isbn: "9781250178602", title: "The Four Winds", author: "Kristin Hannah", co_author: "", series: "", series_number: "", category: "historical_fiction", subcategory: "depression_era", format: "paperback", publisher: "St. Martin's Press", pub_year: 2021, verified: "verified", list_price: 18.99, notes: "" },
  { sku: "NA-039", isbn: "9781984880963", title: "The Thursday Murder Club", author: "Richard Osman", co_author: "", series: "Thursday Murder Club", series_number: "1", category: "thriller_psychological", subcategory: "cozy_mystery", format: "paperback", publisher: "Pamela Dorman Books", pub_year: 2020, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-040", isbn: "9780062868930", title: "The Guest List", author: "Lucy Foley", co_author: "", series: "", series_number: "", category: "thriller_psychological", subcategory: "suspense", format: "paperback", publisher: "William Morrow", pub_year: 2020, verified: "verified", list_price: 17.99, notes: "" },
  { sku: "NA-041", isbn: "9781501154645", title: "Then She Was Gone", author: "Lisa Jewell", co_author: "", series: "", series_number: "", category: "thriller_psychological", subcategory: "suspense", format: "paperback", publisher: "Atria Books", pub_year: 2018, verified: "verified", list_price: 17.99, notes: "" },
  { sku: "NA-042", isbn: "9781594631931", title: "The Kite Runner", author: "Khaled Hosseini", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "book_club", format: "paperback", publisher: "Riverhead Books", pub_year: 2003, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-043", isbn: "9781476738024", title: "A Man Called Ove", author: "Fredrik Backman", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "book_club", format: "paperback", publisher: "Washington Square Press", pub_year: 2012, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-044", isbn: "9780375842207", title: "The Book Thief", author: "Markus Zusak", co_author: "", series: "", series_number: "", category: "historical_fiction", subcategory: "wwii", format: "paperback", publisher: "Knopf Books for Young Readers", pub_year: 2005, verified: "verified", list_price: 12.99, notes: "" },
  { sku: "NA-045", isbn: "9780735224315", title: "Little Fires Everywhere", author: "Celeste Ng", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "book_club", format: "paperback", publisher: "Penguin Press", pub_year: 2017, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-046", isbn: "9780593318171", title: "Klara and the Sun", author: "Kazuo Ishiguro", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "speculative", format: "paperback", publisher: "Vintage", pub_year: 2021, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-047", isbn: "9781455563937", title: "Pachinko", author: "Min Jin Lee", co_author: "", series: "", series_number: "", category: "historical_fiction", subcategory: "family_saga", format: "paperback", publisher: "Grand Central Publishing", pub_year: 2017, verified: "verified", list_price: 18.99, notes: "" },
  { sku: "NA-048", isbn: "9780316055437", title: "The Goldfinch", author: "Donna Tartt", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "contemporary", format: "paperback", publisher: "Little, Brown and Company", pub_year: 2013, verified: "verified", list_price: 20.0, notes: "" },
  { sku: "NA-049", isbn: "9781400031702", title: "The Secret History", author: "Donna Tartt", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "dark_academia", format: "paperback", publisher: "Vintage", pub_year: 1992, verified: "verified", list_price: 18.0, notes: "" },
  { sku: "NA-050", isbn: "9780756404741", title: "The Name of the Wind", author: "Patrick Rothfuss", co_author: "", series: "The Kingkiller Chronicle", series_number: "1", category: "fantasy_epic", subcategory: "high_fantasy", format: "paperback", publisher: "DAW Books", pub_year: 2007, verified: "verified", list_price: 18.0, notes: "" },
  { sku: "NA-051", isbn: "9780553593716", title: "A Game of Thrones", author: "George R.R. Martin", co_author: "", series: "A Song of Ice and Fire", series_number: "1", category: "fantasy_epic", subcategory: "high_fantasy", format: "mass_market", publisher: "Bantam", pub_year: 1996, verified: "verified", list_price: 9.99, notes: "" },
  { sku: "NA-052", isbn: "9780765360960", title: "Mistborn: The Final Empire", author: "Brandon Sanderson", co_author: "", series: "Mistborn", series_number: "1", category: "fantasy_epic", subcategory: "high_fantasy", format: "mass_market", publisher: "Tor Books", pub_year: 2006, verified: "verified", list_price: 9.99, notes: "" },
  { sku: "NA-053", isbn: "9780547928227", title: "The Hobbit", author: "J.R.R. Tolkien", co_author: "", series: "", series_number: "", category: "fantasy_epic", subcategory: "classic_fantasy", format: "paperback", publisher: "Houghton Mifflin", pub_year: 1937, verified: "verified", list_price: 15.99, notes: "" },
  { sku: "NA-054", isbn: "9780441013593", title: "Dune", author: "Frank Herbert", co_author: "", series: "Dune", series_number: "1", category: "science_fiction", subcategory: "space_opera", format: "paperback", publisher: "Ace", pub_year: 1965, verified: "verified", list_price: 18.0, notes: "" },
  { sku: "NA-055", isbn: "9780553418026", title: "The Martian", author: "Andy Weir", co_author: "", series: "", series_number: "", category: "science_fiction", subcategory: "adventure", format: "paperback", publisher: "Broadway Books", pub_year: 2014, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-056", isbn: "9780063021426", title: "Babel", author: "R.F. Kuang", co_author: "", series: "", series_number: "", category: "fantasy_epic", subcategory: "dark_academia", format: "hardcover", publisher: "Harper Voyager", pub_year: 2022, verified: "verified", list_price: 28.99, notes: "" },
  { sku: "NA-057", isbn: "9780062439598", title: "The Hating Game", author: "Sally Thorne", co_author: "", series: "", series_number: "", category: "romance_contemporary", subcategory: "enemies_to_lovers", format: "paperback", publisher: "William Morrow", pub_year: 2016, verified: "verified", list_price: 16.99, notes: "" },
  { sku: "NA-058", isbn: "9781250316776", title: "Red, White & Royal Blue", author: "Casey McQuiston", co_author: "", series: "", series_number: "", category: "romance_contemporary", subcategory: "lgbtq", format: "paperback", publisher: "St. Martin's Griffin", pub_year: 2019, verified: "verified", list_price: 17.99, notes: "" },
  { sku: "NA-059", isbn: "9781984806758", title: "People We Meet on Vacation", author: "Emily Henry", co_author: "", series: "", series_number: "", category: "romance_contemporary", subcategory: "contemporary", format: "paperback", publisher: "Berkley", pub_year: 2021, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-060", isbn: "9780439023528", title: "The Hunger Games", author: "Suzanne Collins", co_author: "", series: "The Hunger Games", series_number: "1", category: "young_adult", subcategory: "dystopian", format: "paperback", publisher: "Scholastic Press", pub_year: 2008, verified: "verified", list_price: 12.99, notes: "" },
  { sku: "NA-061", isbn: "9780525478812", title: "The Fault in Our Stars", author: "John Green", co_author: "", series: "", series_number: "", category: "young_adult", subcategory: "contemporary", format: "paperback", publisher: "Dutton Books", pub_year: 2012, verified: "verified", list_price: 12.99, notes: "" },
  { sku: "NA-062", isbn: "9781627792127", title: "Six of Crows", author: "Leigh Bardugo", co_author: "", series: "Six of Crows", series_number: "1", category: "young_adult", subcategory: "fantasy", format: "paperback", publisher: "Henry Holt and Co.", pub_year: 2015, verified: "verified", list_price: 12.99, notes: "" },
  { sku: "NA-063", isbn: "9780307743657", title: "The Shining", author: "Stephen King", co_author: "", series: "", series_number: "", category: "horror", subcategory: "supernatural", format: "paperback", publisher: "Anchor", pub_year: 1977, verified: "verified", list_price: 9.99, notes: "" },
  { sku: "NA-064", isbn: "9780525620808", title: "Mexican Gothic", author: "Silvia Moreno-Garcia", co_author: "", series: "", series_number: "", category: "horror", subcategory: "gothic", format: "paperback", publisher: "Del Rey", pub_year: 2020, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-065", isbn: "9780062316097", title: "Sapiens: A Brief History of Humankind", author: "Yuval Noah Harari", co_author: "", series: "", series_number: "", category: "literary_nonfiction", subcategory: "history", format: "paperback", publisher: "Harper Perennial", pub_year: 2011, verified: "verified", list_price: 24.99, notes: "" },
  { sku: "NA-066", isbn: "9781524763138", title: "Becoming", author: "Michelle Obama", co_author: "", series: "", series_number: "", category: "literary_nonfiction", subcategory: "memoir", format: "hardcover", publisher: "Crown", pub_year: 2018, verified: "verified", list_price: 32.5, notes: "" },
  { sku: "NA-067", isbn: "9780143127741", title: "The Body Keeps the Score", author: "Bessel van der Kolk", co_author: "", series: "", series_number: "", category: "literary_nonfiction", subcategory: "psychology", format: "paperback", publisher: "Penguin Books", pub_year: 2014, verified: "verified", list_price: 19.0, notes: "" },
  { sku: "NA-068", isbn: "9780141441146", title: "Jane Eyre", author: "Charlotte Brontë", co_author: "", series: "", series_number: "", category: "literary_classic", subcategory: "classic", format: "paperback", publisher: "Penguin Classics", pub_year: 1847, verified: "verified", list_price: 10.0, notes: "" },
  { sku: "NA-069", isbn: "9780060850524", title: "Brave New World", author: "Aldous Huxley", co_author: "", series: "", series_number: "", category: "literary_classic", subcategory: "dystopian", format: "paperback", publisher: "Harper Perennial Modern Classics", pub_year: 1932, verified: "verified", list_price: 16.99, notes: "" },
  { sku: "NA-070", isbn: "9781619630345", title: "Throne of Glass", author: "Sarah J. Maas", co_author: "", series: "Throne of Glass", series_number: "1", category: "fantasy_romance", subcategory: "romantasy", format: "paperback", publisher: "Bloomsbury", pub_year: 2012, verified: "verified", list_price: 14.99, notes: "" },
  { sku: "NA-071", isbn: "9780593441282", title: "Funny Story", author: "Emily Henry", co_author: "", series: "", series_number: "", category: "romance_contemporary", subcategory: "contemporary", format: "hardcover", publisher: "Berkley", pub_year: 2024, verified: "verified", list_price: 29.0, notes: "" },
  { sku: "NA-072", isbn: "9781668026038", title: "Icebreaker", author: "Hannah Grace", co_author: "", series: "Maple Hills", series_number: "1", category: "romance_contemporary", subcategory: "sports", format: "paperback", publisher: "Atria Books", pub_year: 2022, verified: "verified", list_price: 17.99, notes: "" },
  { sku: "NA-073", isbn: "9781542025607", title: "Reminders of Him", author: "Colleen Hoover", co_author: "", series: "", series_number: "", category: "romance_contemporary", subcategory: "book_club", format: "paperback", publisher: "Montlake", pub_year: 2022, verified: "verified", list_price: 16.99, notes: "" },
  { sku: "NA-074", isbn: "9781501171345", title: "The Last Thing He Told Me", author: "Laura Dave", co_author: "", series: "", series_number: "", category: "thriller_psychological", subcategory: "suspense", format: "paperback", publisher: "Simon & Schuster", pub_year: 2021, verified: "verified", list_price: 17.99, notes: "" },
  { sku: "NA-075", isbn: "9781501190100", title: "The Family Upstairs", author: "Lisa Jewell", co_author: "", series: "", series_number: "", category: "thriller_psychological", subcategory: "suspense", format: "paperback", publisher: "Atria Books", pub_year: 2019, verified: "verified", list_price: 17.99, notes: "" },
  { sku: "NA-076", isbn: "9781524745165", title: "Lock Every Door", author: "Riley Sager", co_author: "", series: "", series_number: "", category: "thriller_psychological", subcategory: "suspense", format: "paperback", publisher: "Dutton", pub_year: 2019, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-077", isbn: "9781982179007", title: "None of This Is True", author: "Lisa Jewell", co_author: "", series: "", series_number: "", category: "thriller_psychological", subcategory: "suspense", format: "hardcover", publisher: "Atria Books", pub_year: 2023, verified: "verified", list_price: 28.99, notes: "" },
  { sku: "NA-078", isbn: "9780063250833", title: "Yellowface", author: "R.F. Kuang", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "contemporary", format: "hardcover", publisher: "William Morrow", pub_year: 2023, verified: "verified", list_price: 30.0, notes: "" },
  { sku: "NA-079", isbn: "9780063327528", title: "Tom Lake", author: "Ann Patchett", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "book_club", format: "hardcover", publisher: "Harper", pub_year: 2023, verified: "verified", list_price: 30.0, notes: "" },
  { sku: "NA-080", isbn: "9781250178633", title: "The Women", author: "Kristin Hannah", co_author: "", series: "", series_number: "", category: "historical_fiction", subcategory: "vietnam", format: "hardcover", publisher: "St. Martin's Press", pub_year: 2024, verified: "verified", list_price: 30.0, notes: "" },
  { sku: "NA-081", isbn: "9780593422946", title: "The Heaven & Earth Grocery Store", author: "James McBride", co_author: "", series: "", series_number: "", category: "literary_fiction", subcategory: "book_club", format: "hardcover", publisher: "Riverhead Books", pub_year: 2023, verified: "verified", list_price: 28.0, notes: "" },
  { sku: "NA-082", isbn: "9780316229296", title: "The Fifth Season", author: "N.K. Jemisin", co_author: "", series: "The Broken Earth", series_number: "1", category: "fantasy_epic", subcategory: "high_fantasy", format: "paperback", publisher: "Orbit", pub_year: 2015, verified: "verified", list_price: 18.99, notes: "" },
  { sku: "NA-083", isbn: "9781101904244", title: "Dark Matter", author: "Blake Crouch", co_author: "", series: "", series_number: "", category: "science_fiction", subcategory: "thriller", format: "paperback", publisher: "Broadway Books", pub_year: 2016, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-084", isbn: "9780062662569", title: "The Poppy War", author: "R.F. Kuang", co_author: "", series: "The Poppy War", series_number: "1", category: "fantasy_epic", subcategory: "dark_fantasy", format: "paperback", publisher: "Harper Voyager", pub_year: 2018, verified: "verified", list_price: 18.99, notes: "" },
  { sku: "NA-085", isbn: "9781635575637", title: "Piranesi", author: "Susanna Clarke", co_author: "", series: "", series_number: "", category: "fantasy_epic", subcategory: "literary_fantasy", format: "paperback", publisher: "Bloomsbury", pub_year: 2020, verified: "verified", list_price: 17.0, notes: "" },
  { sku: "NA-086", isbn: "9780399588174", title: "Born a Crime", author: "Trevor Noah", co_author: "", series: "", series_number: "", category: "literary_nonfiction", subcategory: "memoir", format: "paperback", publisher: "Spiegel & Grau", pub_year: 2016, verified: "verified", list_price: 18.0, notes: "" },
  { sku: "NA-087", isbn: "9780807014295", title: "Man's Search for Meaning", author: "Viktor E. Frankl", co_author: "", series: "", series_number: "", category: "literary_nonfiction", subcategory: "psychology", format: "paperback", publisher: "Beacon Press", pub_year: 1946, verified: "verified", list_price: 16.0, notes: "" },
  { sku: "NA-088", isbn: "9780147514011", title: "Little Women", author: "Louisa May Alcott", co_author: "", series: "", series_number: "", category: "literary_classic", subcategory: "classic", format: "paperback", publisher: "Puffin Classics", pub_year: 1868, verified: "verified", list_price: 9.0, notes: "" },
  { sku: "NA-089", isbn: "9780141439570", title: "The Picture of Dorian Gray", author: "Oscar Wilde", co_author: "", series: "", series_number: "", category: "literary_classic", subcategory: "classic", format: "paperback", publisher: "Penguin Classics", pub_year: 1890, verified: "verified", list_price: 11.0, notes: "" },
  { sku: "NA-090", isbn: "9780451526342", title: "Animal Farm", author: "George Orwell", co_author: "", series: "", series_number: "", category: "literary_classic", subcategory: "dystopian", format: "mass_market", publisher: "Signet Classics", pub_year: 1945, verified: "verified", list_price: 9.99, notes: "" },
  { sku: "NA-091", isbn: "9781501142970", title: "It", author: "Stephen King", co_author: "", series: "", series_number: "", category: "horror", subcategory: "supernatural", format: "paperback", publisher: "Scribner", pub_year: 1986, verified: "verified", list_price: 22.0, notes: "" },
  { sku: "NA-092", isbn: "9781982137274", title: "The Spanish Love Deception", author: "Elena Armas", co_author: "", series: "", series_number: "", category: "romance_contemporary", subcategory: "enemies_to_lovers", format: "paperback", publisher: "Atria Books", pub_year: 2021, verified: "verified", list_price: 17.99, notes: "" },
];

export const seedArrivals: SeedArrival[] = rows.map((row, index) => ({
  ...row,
  id: `seed-${row.sku}`,
  cover_url: cover(row.isbn),
  added_at: stagger(index),
}));
